### ISSUE TITLE
Appending Props does not work

### ISSUE THREAD

**Issue by dadingpl** [KcRobin9/MM1-Map-Editor#37]
The other day i was making Cops & Robbers spots for Box Design Raceway (modded map)
i did the code in map editor and wrote this:
app_trailer_1 = {
    "offset": (-76, 10, -1179),
    "face": (-69, 10, -1183),
    "name": Prop.TRAILER}

props_to_append = [app_trailer_1]

compile it and every prop disappear so I debugged BDRW.BNG (before and after)

the prop I added is not on the map but its appearing in the BNG files

[BDRW.BNG (before).txt](https://github.com/user-attachments/files/17396913/BDRW.BNG.before.txt)

[BDRW.BNG (after).txt](https://github.com/user-attachments/files/17396914/BDRW.BNG.after.txt)

the same issue is happening in Chicago

[CHICAGO.BNG.txt](https://github.com/user-attachments/files/17396972/CHICAGO.BNG.txt)

**Comment by KcRobin9** [comment]
Thanks for reporting the issue.
It should be fixed with the next update.
